//! `CollectRefs` — uniform ref-extraction across entity-layer types.
//!
//! Any type that may contain cross-entity refs implements this trait so that
//! `all_refs()` and `all_refs_with_paths()` on tracked entities can traverse
//! nested structures without entity-specific scanning code in other layers.
//!
//! # Convention
//!
//! `collect_refs(prefix, refs)` appends `(sub_path, AnyEntityRef)` pairs into
//! `refs`. `prefix` is the dot-notation path from the current field to the
//! enclosing field name, e.g. `"raci"`. The impl appends child segments as
//! needed: `"raci.accountable"`, `"raci.responsible[0]"`, etc.
//!
//! Types with no entity refs (plain strings, state entries, triggers, …)
//! implement the blanket no-op and contribute nothing.

use std::collections::HashMap;

use indexmap::IndexMap;

use super::{AnyEntityRef, Entity, EntityRef, ParentKind};

pub trait CollectRefs {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>);
}

// ---------------------------------------------------------------------------
// EntityRef<T, P> — the leaf: push itself
// ---------------------------------------------------------------------------

impl<T: Entity<Parent = P>, P: ParentKind> CollectRefs for EntityRef<T, P> {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        refs.push((prefix.to_owned(), self.to_any_ref()));
    }
}

// ---------------------------------------------------------------------------
// Standard container wrappers
// ---------------------------------------------------------------------------

impl<T: CollectRefs> CollectRefs for Option<T> {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        if let Some(inner) = self {
            inner.collect_refs(prefix, refs);
        }
    }
}

impl<T: CollectRefs> CollectRefs for Vec<T> {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        for (i, item) in self.iter().enumerate() {
            item.collect_refs(&format!("{prefix}[{i}]"), refs);
        }
    }
}

/// HashMap: keys and values may each carry refs.
impl<K: CollectRefs, V: CollectRefs> CollectRefs for HashMap<K, V> {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        for (k, v) in self {
            k.collect_refs(prefix, refs);
            v.collect_refs(prefix, refs);
        }
    }
}

/// 2-tuple: each element may carry refs.
impl<A: CollectRefs, B: CollectRefs> CollectRefs for (A, B) {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        self.0.collect_refs(prefix, refs);
        self.1.collect_refs(prefix, refs);
    }
}

/// IndexMap with String keys: folds the key into the child prefix so that
/// e.g. `steps.WriteProposal.entity_ref` is produced from `steps["WriteProposal"].entity_ref`.
impl<V: CollectRefs> CollectRefs for IndexMap<String, V> {
    fn collect_refs(&self, prefix: &str, refs: &mut Vec<(String, AnyEntityRef)>) {
        for (key, val) in self {
            let child = format!("{prefix}.{key}");
            val.collect_refs(&child, refs);
        }
    }
}

// ---------------------------------------------------------------------------
// No-op blanket for primitive / plain-data types
// ---------------------------------------------------------------------------

macro_rules! no_op_collect_refs {
    ($($t:ty),* $(,)?) => {
        $(
            impl CollectRefs for $t {
                fn collect_refs(&self, _prefix: &str, _refs: &mut Vec<(String, AnyEntityRef)>) {}
            }
        )*
    };
}

no_op_collect_refs!(
    String,
    bool,
    u8,
    u16,
    u32,
    u64,
    u128,
    i8,
    i16,
    i32,
    i64,
    i128,
    f32,
    f64,
    serde_json::Value,
);

#[cfg(test)]
mod tests {
    //! Unit coverage for the container wrappers — `Option`, `Vec`,
    //! `HashMap`, tuple, `IndexMap<String, V>`. Path-prefixing is the
    //! interesting bit: tracked-entity rule bodies cite the dotted
    //! path back to callers, so getting `[i]` and `.{key}` segments
    //! right matters. Per-entity collect_refs impls are generated by
    //! `#[derive(CollectRefs)]`; those are exercised end-to-end by
    //! every cross-entity ref test in the functional tier.
    //!
    //! `Role` stands in as the leaf type — it's a simple top-level
    //! entity whose `EntityRef` impl pushes the leaf into the buffer.

    use super::*;
    use crate::entity::entities::role::Role;

    fn role_ref(id: &str) -> EntityRef<Role> {
        EntityRef::<Role>::new(id)
    }

    fn collect<T: CollectRefs>(value: &T, prefix: &str) -> Vec<(String, AnyEntityRef)> {
        let mut out = Vec::new();
        value.collect_refs(prefix, &mut out);
        out
    }

    fn paths(refs: &[(String, AnyEntityRef)]) -> Vec<&str> {
        refs.iter().map(|(p, _)| p.as_str()).collect()
    }

    fn ids(refs: &[(String, AnyEntityRef)]) -> Vec<&str> {
        refs.iter().map(|(_, r)| r.id()).collect()
    }

    // -----------------------------------------------------------------------
    // EntityRef leaf
    // -----------------------------------------------------------------------

    #[test]
    fn entity_ref_pushes_itself_with_prefix() {
        let r = role_ref("eng-lead");
        let out = collect(&r, "raci.accountable");
        assert_eq!(paths(&out), vec!["raci.accountable"]);
        assert_eq!(ids(&out), vec!["eng-lead"]);
    }

    #[test]
    fn entity_ref_with_empty_prefix_pushes_empty_path() {
        let r = role_ref("eng-lead");
        let out = collect(&r, "");
        assert_eq!(paths(&out), vec![""]);
    }

    // -----------------------------------------------------------------------
    // Option<T>
    // -----------------------------------------------------------------------

    #[test]
    fn option_none_contributes_nothing() {
        let v: Option<EntityRef<Role>> = None;
        assert!(collect(&v, "field").is_empty());
    }

    #[test]
    fn option_some_delegates_with_same_prefix() {
        let v = Some(role_ref("eng-lead"));
        let out = collect(&v, "field");
        assert_eq!(paths(&out), vec!["field"]);
    }

    // -----------------------------------------------------------------------
    // Vec<T>
    // -----------------------------------------------------------------------

    #[test]
    fn vec_empty_contributes_nothing() {
        let v: Vec<EntityRef<Role>> = vec![];
        assert!(collect(&v, "responsible").is_empty());
    }

    #[test]
    fn vec_appends_index_segment_per_item() {
        let v = vec![role_ref("a"), role_ref("b"), role_ref("c")];
        let out = collect(&v, "responsible");
        assert_eq!(
            paths(&out),
            vec!["responsible[0]", "responsible[1]", "responsible[2]"]
        );
        assert_eq!(ids(&out), vec!["a", "b", "c"]);
    }

    // -----------------------------------------------------------------------
    // HashMap<K, V>
    // -----------------------------------------------------------------------

    #[test]
    fn hashmap_collects_from_both_keys_and_values() {
        // HashMap<EntityRef<Role>, EntityRef<Role>> uses the same
        // prefix for both sides — keys and values both contribute,
        // there's no `[k]` / `[v]` distinction in the path.
        let mut m: HashMap<EntityRef<Role>, EntityRef<Role>> = HashMap::new();
        m.insert(role_ref("k1"), role_ref("v1"));
        let out = collect(&m, "field");
        assert_eq!(out.len(), 2);
        for (path, _) in &out {
            assert_eq!(path, "field");
        }
        let mut found_ids: Vec<&str> = ids(&out);
        found_ids.sort();
        assert_eq!(found_ids, vec!["k1", "v1"]);
    }

    #[test]
    fn hashmap_no_op_keys_only_values_contribute() {
        // String keys are no-op; only values contribute refs.
        let mut m: HashMap<String, EntityRef<Role>> = HashMap::new();
        m.insert("a".to_string(), role_ref("eng-lead"));
        let out = collect(&m, "field");
        assert_eq!(paths(&out), vec!["field"]);
        assert_eq!(ids(&out), vec!["eng-lead"]);
    }

    // -----------------------------------------------------------------------
    // (A, B) tuple
    // -----------------------------------------------------------------------

    #[test]
    fn tuple_both_elements_contribute_with_same_prefix() {
        let t = (role_ref("a"), role_ref("b"));
        let out = collect(&t, "include[0]");
        assert_eq!(paths(&out), vec!["include[0]", "include[0]"]);
        assert_eq!(ids(&out), vec!["a", "b"]);
    }

    #[test]
    fn tuple_no_op_left_only_right_contributes() {
        let t = ("name".to_string(), role_ref("eng-lead"));
        let out = collect(&t, "field");
        assert_eq!(paths(&out), vec!["field"]);
        assert_eq!(ids(&out), vec!["eng-lead"]);
    }

    // -----------------------------------------------------------------------
    // IndexMap<String, V>
    // -----------------------------------------------------------------------

    #[test]
    fn indexmap_string_keyed_folds_key_into_prefix() {
        // The convention is `prefix.{key}` — keys become path segments.
        let mut m: IndexMap<String, EntityRef<Role>> = IndexMap::new();
        m.insert("WriteProposal".to_string(), role_ref("author"));
        m.insert("Review".to_string(), role_ref("approver"));
        let out = collect(&m, "steps");
        // IndexMap preserves insertion order; assert paths in order.
        assert_eq!(paths(&out), vec!["steps.WriteProposal", "steps.Review"]);
        assert_eq!(ids(&out), vec!["author", "approver"]);
    }

    #[test]
    fn indexmap_empty_contributes_nothing() {
        let m: IndexMap<String, EntityRef<Role>> = IndexMap::new();
        assert!(collect(&m, "steps").is_empty());
    }

    // -----------------------------------------------------------------------
    // No-op blanket
    // -----------------------------------------------------------------------

    #[test]
    fn primitive_types_contribute_nothing() {
        assert!(collect(&"name".to_string(), "field").is_empty());
        assert!(collect(&42u32, "count").is_empty());
        assert!(collect(&true, "flag").is_empty());
        assert!(collect(&serde_json::json!({"x-foo": 1}), "extensions").is_empty());
    }

    // -----------------------------------------------------------------------
    // Composition — nested wrappers exercise the prefix-threading
    // -----------------------------------------------------------------------

    #[test]
    fn nested_option_vec_indexmap_threads_path_segments_correctly() {
        // Mirrors what a real workflow's `steps` field looks like:
        // an IndexMap<String, V> whose value carries a Vec of
        // EntityRef. Path segments must compose left-to-right.
        let mut m: IndexMap<String, Option<Vec<EntityRef<Role>>>> = IndexMap::new();
        m.insert(
            "Review".to_string(),
            Some(vec![role_ref("a"), role_ref("b")]),
        );
        let out = collect(&m, "steps");
        assert_eq!(paths(&out), vec!["steps.Review[0]", "steps.Review[1]"]);
    }
}
