//! [`EntityRef`] — typed, parent-aware handle for every entity in the system.
//!
//! `EntityRef` is the one handle type passed around between layers. Carrying
//! both entity type and parent kind in the type parameters keeps the
//! runtime cost to a `String` + parent value while preventing whole classes
//! of mix-ups at the type level — a `EntityRef<Task, WorkflowParent>` cannot
//! be swapped for a `EntityRef<Role>` in any API that consumes it.

use std::marker::PhantomData;

use super::{AnyEntityRef, Entity, EntityKind, NoParent, ParentKind};
use crate::error::primitive::PrimitiveError;

/// A typed reference to an entity: its string id plus its parent context.
///
/// The two constructors model the two identity shapes in the system:
/// [`EntityRef::new`] for top-level entities (`P = NoParent`) and
/// [`EntityRef::with_parent`] for embedded entities. Hash and `Eq`
/// incorporate `T::KIND` and the full parent, so refs of different kinds —
/// or the same kind under different parents — never collide as map keys.
///
/// Serde produces a uniform `{ id, kind, parent? }` object regardless of
/// instantiation; the generated JSON Schema constrains the id pattern per
/// entity kind.
pub struct EntityRef<T: Entity, P: ParentKind = NoParent> {
    pub(crate) id: String,
    pub(crate) parent: P,
    _marker: PhantomData<fn() -> T>,
}

impl<T: Entity> EntityRef<T, NoParent> {
    /// Construct a top-level entity reference.
    pub fn new(id: impl Into<String>) -> Self {
        Self::with_parent(id, NoParent)
    }
}

impl<T: Entity, P: ParentKind> EntityRef<T, P> {
    /// Construct an entity reference with an explicit parent value.
    pub fn with_parent(id: impl Into<String>, parent: P) -> Self {
        Self {
            id: id.into(),
            parent,
            _marker: PhantomData,
        }
    }

    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn parent(&self) -> Option<&P> {
        self.parent.value()
    }

    /// Convert this typed ref into the type-erased [`AnyEntityRef`].
    ///
    /// Per-kind variant construction is generated by `#[derive(Entity)]`
    /// behind the [`Entity::to_any_ref`] hook; this method is the
    /// ergonomic call form callers use.
    pub fn to_any_ref(&self) -> AnyEntityRef
    where
        T: Entity<Parent = P>,
    {
        <T as Entity>::to_any_ref(self)
    }

    pub(crate) fn from_serialized_parts(
        id: Option<String>,
        kind: Option<String>,
        parent: Option<serde_json::Value>,
    ) -> Result<Self, PrimitiveError> {
        let id = id.ok_or_else(|| {
            PrimitiveError::missing_required_reference_field(
                "missing required reference field",
                "id",
            )
        })?;
        let kind = kind.ok_or_else(|| {
            PrimitiveError::missing_required_reference_field(
                "missing required reference field",
                "kind",
            )
        })?;
        if kind != T::KIND.as_str() {
            return Err(PrimitiveError::unknown_entity_kind_tag(
                "unknown entity kind tag",
                kind,
            ));
        }
        let parent = P::deserialize_parent(parent, T::KIND.as_str())?;
        Ok(EntityRef::with_parent(id, parent))
    }
}

impl<T: Entity, P: ParentKind + PartialEq> PartialEq for EntityRef<T, P> {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id && self.parent == other.parent
    }
}

impl<T: Entity, P: ParentKind + Eq> Eq for EntityRef<T, P> {}

impl<T: Entity, P: ParentKind + std::hash::Hash> std::hash::Hash for EntityRef<T, P> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        T::KIND.hash(state);
        self.id.hash(state);
        self.parent.hash(state);
    }
}

impl<T: Entity, P: ParentKind + Clone> Clone for EntityRef<T, P> {
    fn clone(&self) -> Self {
        Self {
            id: self.id.clone(),
            parent: self.parent.clone(),
            _marker: PhantomData,
        }
    }
}

impl<T: Entity, P: ParentKind + std::fmt::Debug> std::fmt::Debug for EntityRef<T, P> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EntityRef")
            .field("kind", &T::KIND)
            .field("id", &self.id)
            .field("parent", &self.parent)
            .finish()
    }
}

impl<T: Entity, P: ParentKind> serde::Serialize for EntityRef<T, P> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;

        let mut map = s.serialize_map(None)?;
        map.serialize_entry("id", &self.id)?;
        map.serialize_entry("kind", T::KIND.as_str())?;
        self.parent.serialize_parent(&mut map)?;
        map.end()
    }
}

impl<'de, T: Entity, P: ParentKind> serde::Deserialize<'de> for EntityRef<T, P> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use std::fmt;

        use serde::de::{MapAccess, Visitor};

        struct V<T, P>(std::marker::PhantomData<(T, P)>);

        impl<'de, T: Entity, P: ParentKind> Visitor<'de> for V<T, P> {
            type Value = EntityRef<T, P>;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "an entity ref object")
            }

            fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<EntityRef<T, P>, A::Error> {
                let mut id: Option<String> = None;
                let mut kind: Option<String> = None;
                let mut parent: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "id" => id = Some(map.next_value()?),
                        "kind" => kind = Some(map.next_value()?),
                        "parent" => parent = Some(map.next_value()?),
                        _ => {
                            let _: serde_json::Value = map.next_value()?;
                        }
                    }
                }
                EntityRef::from_serialized_parts(id, kind, parent).map_err(serde::de::Error::custom)
            }
        }

        d.deserialize_map(V::<T, P>(std::marker::PhantomData))
    }
}

impl<T, P> schemars::JsonSchema for EntityRef<T, P>
where
    T: Entity,
    P: ParentKind + schemars::JsonSchema + 'static,
{
    fn schema_name() -> String {
        format!("{}EntityRef", T::KIND.as_str())
    }

    fn json_schema(gen: &mut schemars::gen::SchemaGenerator) -> schemars::schema::Schema {
        use schemars::schema::{
            InstanceType, Metadata, ObjectValidation, Schema, SchemaObject, SingleOrVec,
            StringValidation,
        };

        let mut properties = schemars::Map::new();
        let id_pattern = match T::KIND {
            EntityKind::Role | EntityKind::Hook | EntityKind::Team | EntityKind::ArtifactKind => {
                "^[a-z][a-z0-9-]*$"
            }
            EntityKind::Workflow
            | EntityKind::ReusableWorkflow
            | EntityKind::Task
            | EntityKind::Relay
            | EntityKind::EmbeddedWorkflow => "^[A-Z][A-Za-z0-9]*$",
        };
        properties.insert(
            "id".to_string(),
            Schema::Object(SchemaObject {
                instance_type: Some(SingleOrVec::Single(Box::new(InstanceType::String))),
                string: Some(Box::new(StringValidation {
                    pattern: Some(id_pattern.to_string()),
                    ..Default::default()
                })),
                ..Default::default()
            }),
        );
        properties.insert(
            "kind".to_string(),
            Schema::Object(SchemaObject {
                instance_type: Some(SingleOrVec::Single(Box::new(InstanceType::String))),
                enum_values: Some(vec![serde_json::Value::String(
                    T::KIND.as_str().to_string(),
                )]),
                ..Default::default()
            }),
        );

        let mut required = schemars::Set::new();
        required.insert("id".to_string());
        required.insert("kind".to_string());

        if std::any::TypeId::of::<P>() != std::any::TypeId::of::<NoParent>() {
            properties.insert("parent".to_string(), gen.subschema_for::<P>());
            required.insert("parent".to_string());
        }

        Schema::Object(SchemaObject {
            metadata: Some(Box::new(Metadata {
                title: Some(Self::schema_name()),
                ..Default::default()
            })),
            instance_type: Some(SingleOrVec::Single(Box::new(InstanceType::Object))),
            object: Some(Box::new(ObjectValidation {
                properties,
                required,
                ..Default::default()
            })),
            ..Default::default()
        })
    }
}
