//! The [`Entity`] trait and its tracked-companion roundtrip.
//!
//! `#[derive(Entity)]` produces all the impls here. Hand-writing an [`Entity`]
//! is not supported — too much of the generated surface (tracked companion,
//! serde, dispatch) would need to be replicated by hand.

use super::{AnyEntityRef, EntityKind, EntityRef, ParentKind, TrackedEntity};

/// Every plain entity struct in the system implements this.
///
/// Associates each entity with its [`EntityKind`] discriminant, its parent
/// kind, its validation schema, and its tracked companion. Provides the two
/// dispatch hooks that let typed code move between [`EntityRef`]s and the
/// type-erased [`AnyEntityRef`] / [`TrackedEntity`] enums without per-kind
/// match arms outside the generated registry.
pub trait Entity: Sized + 'static {
    const KIND: EntityKind;
    fn validation_schema() -> &'static crate::validation::ValidationSchema<Self>;
    type Parent: ParentKind;
    type Tracked: TrackedFor<Entity = Self>;
    /// The mutation handle handed back by `EntityClient::checkout`. Owns
    /// the checked-out entity, exposes setters, and consumes itself on
    /// `commit` or `undo_checkout`. Generated by `#[derive(Entity)]`.
    type Delegate;

    /// Convert a typed EntityRef to the type-erased AnyEntityRef.
    /// Generated by `#[derive(Entity)]`.
    fn to_any_ref(entity_ref: &EntityRef<Self, Self::Parent>) -> AnyEntityRef;

    /// Extract this entity's tracked form from a TrackedEntity.
    /// Returns None if the variant doesn't match.
    /// Generated by `#[derive(Entity)]`.
    fn extract(entity: &TrackedEntity) -> Option<&Self::Tracked>;

    /// Take this entity's tracked form by value out of a TrackedEntity.
    /// Returns the original entity back if the variant doesn't match.
    /// Generated by `#[derive(Entity)]`.
    fn take(entity: TrackedEntity) -> Result<Self::Tracked, TrackedEntity>;

    /// Wrap a tracked instance back into a TrackedEntity. Generated by
    /// `#[derive(Entity)]`.
    fn into_tracked_entity(tracked: Self::Tracked) -> TrackedEntity;
}

/// Inverse of [`Entity::Tracked`]. Lets generic code start from a tracked
/// companion and recover its plain entity type: `T::Entity::Tracked = T`.
pub trait TrackedFor {
    type Entity: Entity<Tracked = Self>;
}

/// Ergonomic alias: `Tracked<Role>` reads better than
/// `<Role as Entity>::Tracked` at call sites.
pub type Tracked<T> = <T as Entity>::Tracked;
