use super::{AnyEntityRef, EntityKind, EntityRef, ParentKind, TrackedEntity};

pub trait Entity: Sized + 'static {
    const KIND: EntityKind;
    fn validation_schema() -> &'static crate::validation::ValidationSchema<Self>;
    type Parent: ParentKind;
    type Tracked: TrackedFor<Entity = Self>;

    /// Convert a typed EntityRef to the type-erased AnyEntityRef.
    /// Generated by `#[derive(Entity)]`.
    fn to_any_ref(entity_ref: &EntityRef<Self, Self::Parent>) -> AnyEntityRef;

    /// Extract this entity's tracked form from a TrackedEntity.
    /// Returns None if the variant doesn't match.
    /// Generated by `#[derive(Entity)]`.
    fn extract(entity: &TrackedEntity) -> Option<&Self::Tracked>;
}

/// Implemented by every tracked entity struct.
/// Provides the roundtrip: `TrackedRole::Entity = Role`
/// and therefore `Role::Tracked::Entity = Role`.
pub trait TrackedFor {
    type Entity: Entity<Tracked = Self>;
}

/// Ergonomic alias: `Tracked<Role>` instead of `<Role as Entity>::Tracked`.
pub type Tracked<T> = <T as Entity>::Tracked;
