//! [`XEditor<'ws, T>`] — workspace-bound mutation handle.
//!
//! An editor wraps an [`XViewer`] for read access (via `Deref`) and
//! adds per-field setters and the `commit(self)` / `undo_checkout(self)`
//! lifecycle. Editors are returned only by [`Workspace::checkout`];
//! they are not `Clone` and consume themselves on lifecycle terminators.
//!
//! Per-field setters (`set_<field>(&mut self, value)`) are generated by
//! `#[derive(Entity)]` per entity type. Their bodies dispatch
//! `EnsureMutable` and validate against a transient candidate viewer
//! before swapping the field's `Arc<TrackedField<_>>`.

use std::ops::Deref;

use crate::{entity::Entity, workspace::viewer::XViewer};

/// Mutation handle returned by [`Workspace::checkout`](crate::workspace::Workspace::checkout).
///
/// Owns the checked-out [`XViewer`] (which in turn owns the tracked
/// state). `Deref`s to the viewer so generated read accessors and
/// `validate` / `validate_with` are reachable. Setters and the
/// consume-on-finish lifecycle live on the editor.
pub struct XEditor<'ws, T: Entity> {
    pub(crate) viewer: XViewer<'ws, T>,
}

impl<'ws, T: Entity> XEditor<'ws, T> {
    pub(crate) fn new(viewer: XViewer<'ws, T>) -> Self {
        Self { viewer }
    }

    /// Mutable access to the wrapped viewer. Macro-internal — used by
    /// generated setters in downstream crates that cannot see the
    /// `pub(crate)` field directly.
    #[doc(hidden)]
    pub fn __viewer_mut(&mut self) -> &mut XViewer<'ws, T> {
        &mut self.viewer
    }

    /// Consume the editor and return the wrapped viewer. Macro-internal
    /// — used by `commit(self)` / `undo_checkout(self)` so generated
    /// code can hand the tracked entity to the store.
    #[doc(hidden)]
    pub fn __into_viewer(self) -> XViewer<'ws, T> {
        self.viewer
    }
}

impl<'ws, T: Entity> Deref for XEditor<'ws, T> {
    type Target = XViewer<'ws, T>;
    fn deref(&self) -> &XViewer<'ws, T> {
        &self.viewer
    }
}
