//! Caller-facing async API over the entity server.
//!
//! Every external consumer drives Pari through this layer. Three surfaces
//! cover the full interaction:
//!
//! - [`EntityClient`] — typed operations keyed by `AnyEntityRef`, plus
//!   the generic `checkout<T>` that returns the entity's per-type
//!   `Delegate`.
//! - Per-entity `XDelegate` methods — setters, `commit`, and
//!   `undo_checkout`. Generated by `#[derive(Entity)]`.
//! - `#[derive(Entity)]`-generated accessors on the tracked companion —
//!   transparent per-field load. Reachable from a delegate via `Deref`.
//!
//! No entity state lives here: the layer is stateless plumbing that builds
//! store messages, awaits replies, and forwards typed results to callers.
//! Setters additionally run structural and semantic
//! [`validation`](crate::validation) synchronously against a candidate
//! before swapping the field.
//!
//! See `docs/design/layers/workspace.md` for the L3 design.

mod client;
pub mod lib;

pub use client::EntityClient;
