//! [`XViewer<'ws, T>`] — workspace-bound read handle to a typed entity.
//!
//! A viewer wraps an owned [`Tracked<T>`](crate::entity::Tracked) (the
//! entity-layer state companion) and a `&'ws Workspace` it borrows.
//! Per-field async accessors generated by `#[derive(Entity)]` live on
//! the viewer; their bodies dispatch loads through `self.workspace`.
//!
//! Viewers are returned by [`Workspace::resolve`], [`Workspace::remove`],
//! and [`Workspace::import`]. They cannot outlive the workspace they
//! borrow, so a viewer leaving its session is a compile-time error.

use crate::{entity::Entity, workspace::Workspace};

/// Read-only, workspace-bound handle to a typed entity.
pub struct XViewer<'ws, T: Entity> {
    pub(crate) inner: <T as Entity>::Tracked,
    pub(crate) workspace: &'ws Workspace,
}

impl<'ws, T: Entity> XViewer<'ws, T> {
    pub(crate) fn new(inner: <T as Entity>::Tracked, workspace: &'ws Workspace) -> Self {
        Self { inner, workspace }
    }

    /// The workspace this viewer borrows. Cross-entity validation rules
    /// reach the store through `viewer.workspace().resolve(other_ref).await`.
    pub fn workspace(&self) -> &Workspace {
        self.workspace
    }

    /// The owned tracked-state companion. Per-type generated accessors
    /// (`viewer.field().await`) project through this.
    pub fn tracked(&self) -> &<T as Entity>::Tracked {
        &self.inner
    }
}
