//! [`XViewer<'ws, T>`] — workspace-bound read handle to a typed entity.
//!
//! A viewer wraps an owned [`Tracked<T>`](crate::entity::Tracked) (the
//! entity-layer state companion) and a `&'ws Workspace` it borrows.
//! Per-field async accessors generated by `#[derive(Entity)]` live on
//! the viewer; their bodies dispatch loads through `self.workspace`.
//!
//! Viewers are returned by [`Workspace::resolve`], [`Workspace::remove`],
//! and [`Workspace::import`]. They cannot outlive the workspace they
//! borrow, so a viewer leaving its session is a compile-time error.

use crate::{
    entity::Entity,
    error::ActivityError,
    validation::{lib::schema::ValidatableTracked, ValidationKind},
    workspace::Workspace,
};

/// Read-only, workspace-bound handle to a typed entity.
pub struct XViewer<'ws, T: Entity> {
    pub(crate) inner: <T as Entity>::Tracked,
    pub(crate) workspace: &'ws Workspace,
}

impl<'ws, T: Entity> XViewer<'ws, T> {
    pub(crate) fn new(inner: <T as Entity>::Tracked, workspace: &'ws Workspace) -> Self {
        Self { inner, workspace }
    }

    /// The workspace this viewer borrows. Cross-entity validation rules
    /// reach the store through `viewer.workspace().resolve(other_ref).await`.
    pub fn workspace(&self) -> &Workspace {
        self.workspace
    }

    /// The owned tracked-state companion. Per-type generated accessors
    /// (`viewer.field().await`) project through this.
    pub fn tracked(&self) -> &<T as Entity>::Tracked {
        &self.inner
    }

    /// Mutable access to the tracked companion. Macro-internal — used
    /// by generated `XEditor` setters in downstream crates that cannot
    /// see the `pub(crate)` field directly.
    #[doc(hidden)]
    pub fn __tracked_mut(&mut self) -> &mut <T as Entity>::Tracked {
        &mut self.inner
    }

    /// Move out of the viewer, returning the owned tracked companion.
    /// Macro-internal — used by `XEditor::commit(self)` to hand the
    /// tracked entity to the store.
    #[doc(hidden)]
    pub fn __into_inner(self) -> <T as Entity>::Tracked {
        self.inner
    }

    /// Run the schema's full kind set (Structural + Semantic +
    /// CrossEntity) over every loaded field.
    pub async fn validate(&self) -> Result<(), ActivityError>
    where
        <T as Entity>::Tracked: ValidatableTracked<T>,
    {
        self.validate_with(
            &[],
            &[
                ValidationKind::Structural,
                ValidationKind::Semantic,
                ValidationKind::CrossEntity,
            ],
        )
        .await
    }

    /// Parameterised runner entry. `fields == &[]` means "every field
    /// in the schema"; `kinds` selects which rule kinds to run.
    pub async fn validate_with(
        &self,
        fields: &[&str],
        kinds: &[ValidationKind],
    ) -> Result<(), ActivityError>
    where
        <T as Entity>::Tracked: ValidatableTracked<T>,
    {
        crate::validation::run_validations::<T>(self, fields, kinds).await
    }
}
