//! `ErrorCompose` — the structural contract every Pari error implements.
//!
//! `ErrorCompose` serves two jobs and nothing else:
//!
//! 1. Expose classification (`fix_domain`, `recoverability`, `severity`) so
//!    callers can decide how to react without matching on concrete types.
//! 2. Support [`as_error<E>()`](ErrorCompose#method.as_error) so callers can
//!    reach into a composed chain and pull out a specific concrete primitive
//!    or activity type for typed inspection.
//!
//! Observability is deliberately *not* here — that is [`OTelEmit`]'s job.
//! Keeping the two split lets tests exercise classification without touching
//! tracing, and lets emission evolve without reshaping the caller-facing
//! classification contract.
//!
//! Every implementation in the codebase is generated by
//! `#[derive(ErrorCompose)]`; this module defines the shape those derives fill
//! in.
//!
//! [`OTelEmit`]: super::OTelEmit

use super::{FixDomain, Recoverability, Severity};

/// The structural contract for every error that participates in Pari's
/// composed chain. See the [module-level docs](self) for the big picture.
pub trait ErrorCompose: sealed::AsAny + std::error::Error + Send + Sync + 'static {
    /// Which domain owns the fix for this error.
    fn fix_domain(&self) -> FixDomain;

    /// What the caller should do about this error.
    fn recoverability(&self) -> Recoverability;

    /// Derived log-level classification. Always a function of the two axes
    /// above — do not override.
    fn severity(&self) -> Severity {
        Severity::from_classification(self.fix_domain(), self.recoverability())
    }

    /// Exposes the wrapped inner error for delegating enum variants, so that
    /// [`as_error<E>()`](ErrorCompose#method.as_error) can traverse through
    /// one layer of wrapping during downcasting.
    ///
    /// Default `None` — overridden by `#[derive(ErrorCompose)]` on enums whose
    /// variants are declared `#[compose(delegate)]`.
    fn as_any_inner(&self) -> Option<&dyn std::any::Any> {
        None
    }
}

impl dyn ErrorCompose {
    /// Downcast the composed error to a specific concrete type.
    ///
    /// Use this when a caller has a boxed or generic error and needs typed
    /// access to a leaf — for example, a test asserting that a primitive
    /// `AssetWrite` is somewhere in the chain, or a caller inspecting the
    /// fields of a specific activity variant.
    ///
    /// The lookup checks the current node first, then the immediately wrapped
    /// inner value (for delegating enums). It does not recurse further — to
    /// reach across more than one wrapper, chain the calls:
    ///
    /// ```ignore
    /// let activity = err.as_error::<ActivityError>()?;
    /// let primitive = (activity as &dyn ErrorCompose).as_error::<PrimitiveError>()?;
    /// ```
    pub fn as_error<E: 'static>(&self) -> Option<&E> {
        if let Some(e) = self.as_any().downcast_ref::<E>() {
            return Some(e);
        }
        self.as_any_inner()?.downcast_ref::<E>()
    }
}

mod sealed {
    pub trait AsAny: 'static {
        fn as_any(&self) -> &dyn std::any::Any;
    }
    impl<T: 'static> AsAny for T {
        fn as_any(&self) -> &dyn std::any::Any {
            self
        }
    }
}
