//! `OTelEmit` — the observability-emission contract.
//!
//! `OTelEmit` is the counterpart to [`ErrorCompose`] and owns exactly one
//! concern: turning a composed error chain into a single structured OTel event.
//! Classification, downcasting, and the `source()` chain itself belong to
//! `ErrorCompose`; field emission belongs here.
//!
//! Callers invoke [`emit()`](OTelEmit::emit) once — typically at the Job tier,
//! at the point where Pari's result reaches the integration surface. The
//! generated implementation cascades through the chain: every tier contributes
//! its own fields, all of which land in one event on the active tracing span.
//!
//! Field names follow OTel semantic conventions where one exists, and are
//! otherwise namespaced by error type (`error.<error_type>.<field>`) so that
//! multiple tiers can contribute structured fields without colliding. See
//! [`docs/design/layers/error-handling.md`](../../../../docs/design/layers/error-handling.md#field-name-conventions)
//! for the full naming table.
//!
//! Every implementation in the codebase is generated by `#[derive(OTelEmit)]`.
//!
//! [`ErrorCompose`]: super::ErrorCompose

/// Emit a composed error chain as a single structured OTel event.
pub trait OTelEmit {
    /// Emit this error's fields into the active tracing span, then cascade to
    /// the wrapped inner error so the full chain contributes to one event.
    fn emit(&self);
}
