//! Entity identity infrastructure.
//!
//! [`Entity`] — core trait every entity type implements.
//! [`TrackedFor`] — companion trait linking `Tracked*` structs back to their entity type.
//! [`EntityRef`] — typed reference (id + optional parent chain).
//! [`EntityKind`] — discriminant enum for all entity types.
//! [`StoreEntity`] — store-level enum wrapping all tracked entity types.
//! [`ParentKind`] — sealed trait for parent type parameters.

use std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Re-exports from validation module (Task 06)
// ---------------------------------------------------------------------------

// ValidationSchema, LoadError, SetterError re-exported so that proc-macro
// generated code using `::pari::entity::ValidationSchema` etc. resolves here.
pub use crate::workspace::error::LoadError;
pub use crate::validation::error::SetterError;
pub use crate::validation::ValidationSchema;

// ---------------------------------------------------------------------------
// Sealed
// ---------------------------------------------------------------------------

mod private {
    pub trait Sealed {}
}

use crate::entities::{
    artifact_kind::{ArtifactKind, TrackedArtifactKind},
    hook::{Hook, TrackedHook},
    relay::{Relay, TrackedRelay},
    role::{Role, TrackedRole},
    task::{Task, TrackedTask},
    team::{Team, TrackedTeam},
    workflow::{
        EmbeddedWorkflow, ReusableWorkflow, TrackedEmbeddedWorkflow, TrackedReusableWorkflow,
        TrackedWorkflow, Workflow,
    },
};

// ---------------------------------------------------------------------------
// ParentKind
// ---------------------------------------------------------------------------

/// Marker trait for parent type parameters on EntityRef.
pub trait ParentKind: private::Sealed + Clone + PartialEq + Eq + std::hash::Hash + std::fmt::Debug {
    fn serialize_parent<M: serde::ser::SerializeMap>(&self, map: &mut M) -> Result<(), M::Error>;
    fn deserialize_parent<E>(parent: Option<serde_json::Value>) -> Result<Self, E>
    where
        Self: Sized,
        E: serde::de::Error;
    fn value(&self) -> Option<&Self>;
}

/// Top-level entities have no parent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct NoParent;
impl private::Sealed for NoParent {}
impl ParentKind for NoParent {
    fn serialize_parent<M: serde::ser::SerializeMap>(&self, _map: &mut M) -> Result<(), M::Error> {
        Ok(())
    }

    fn deserialize_parent<E>(parent: Option<serde_json::Value>) -> Result<Self, E>
    where
        E: serde::de::Error,
    {
        if parent.is_some() {
            return Err(E::unknown_field("parent", &["id", "kind"]));
        }
        Ok(NoParent)
    }

    fn value(&self) -> Option<&Self> {
        None
    }
}

/// Closed parent hierarchy for embedded entities in the workflow tree.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum WorkflowParent {
    Workflow(EntityRef<Workflow, NoParent>),
    ReusableWorkflow(EntityRef<ReusableWorkflow, NoParent>),
    EmbeddedWorkflow(Box<EntityRef<EmbeddedWorkflow, WorkflowParent>>),
}
impl private::Sealed for WorkflowParent {}
impl ParentKind for WorkflowParent {
    fn serialize_parent<M: serde::ser::SerializeMap>(&self, map: &mut M) -> Result<(), M::Error> {
        map.serialize_entry("parent", self)
    }

    fn deserialize_parent<E>(parent: Option<serde_json::Value>) -> Result<Self, E>
    where
        E: serde::de::Error,
    {
        let parent = parent.ok_or_else(|| E::missing_field("parent"))?;
        serde_json::from_value(parent).map_err(E::custom)
    }

    fn value(&self) -> Option<&Self> {
        Some(self)
    }
}

// ---------------------------------------------------------------------------
// Real entity types — imported from crate::entities (Task 05+).
// EntityKind, AnyEntityRef, StoreEntity, SubstrateSchema, and load_strategy
// are all generated by the entity_registry! invocation below.
// ---------------------------------------------------------------------------

pari_macros::entity_registry! {
    Role             => NoParent,
    Hook             => NoParent,
    Team             => NoParent,
    Workflow         => NoParent,
    ReusableWorkflow => NoParent,
    ArtifactKind     => NoParent,
    Task             => WorkflowParent,
    Relay            => WorkflowParent,
    EmbeddedWorkflow => WorkflowParent,
}

// ---------------------------------------------------------------------------
// Entity trait
// ---------------------------------------------------------------------------

pub trait Entity: Sized + 'static {
    const KIND: EntityKind;
    fn validation_schema() -> &'static ValidationSchema<Self>;
    type Parent: ParentKind;
    type Tracked: TrackedFor<Entity = Self>;

    /// Convert a typed EntityRef to the type-erased AnyEntityRef.
    /// Generated by `#[derive(Entity)]`.
    fn to_any_ref(entity_ref: &EntityRef<Self, Self::Parent>) -> AnyEntityRef;

    /// Extract this entity's tracked form from a StoreEntity.
    /// Returns None if the variant doesn't match.
    /// Generated by `#[derive(Entity)]`.
    fn extract(entity: &StoreEntity) -> Option<&Self::Tracked>;
}

// ---------------------------------------------------------------------------
// TrackedFor companion trait
// ---------------------------------------------------------------------------

/// Implemented by every tracked entity struct.
/// Provides the roundtrip: `TrackedRole::Entity = Role`
/// and therefore `Role::Tracked::Entity = Role`.
pub trait TrackedFor {
    type Entity: Entity<Tracked = Self>;
}

// ---------------------------------------------------------------------------
// Tracked<T> type alias
// ---------------------------------------------------------------------------

/// Ergonomic alias: `Tracked<Role>` instead of `<Role as Entity>::Tracked`.
pub type Tracked<T> = <T as Entity>::Tracked;

// ---------------------------------------------------------------------------
// EntityRef<T, P>
// ---------------------------------------------------------------------------

/// A typed reference to an entity: its string id and optional parent context.
///
/// `T: Entity` ensures only declared entity types can form refs.
/// `P = NoParent` default covers top-level entities.
///
/// Hash and Eq incorporate `T::KIND` so refs of different entity types with
/// the same id do not collide as HashMap keys.
pub struct EntityRef<T: Entity, P: ParentKind = NoParent> {
    pub(crate) id: String,
    pub(crate) parent: P,
    _marker: PhantomData<fn() -> T>,
}

impl<T: Entity> EntityRef<T, NoParent> {
    /// Construct a top-level entity reference.
    pub fn new(id: impl Into<String>) -> Self {
        Self::with_parent(id, NoParent)
    }
}

impl<T: Entity, P: ParentKind> EntityRef<T, P> {
    /// Construct an entity reference with an explicit parent value.
    pub fn with_parent(id: impl Into<String>, parent: P) -> Self {
        Self { id: id.into(), parent, _marker: PhantomData }
    }

    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn parent(&self) -> Option<&P> {
        self.parent.value()
    }
}

impl<T: Entity, P: ParentKind + PartialEq> PartialEq for EntityRef<T, P> {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id && self.parent == other.parent
    }
}

impl<T: Entity, P: ParentKind + Eq> Eq for EntityRef<T, P> {}

impl<T: Entity, P: ParentKind + std::hash::Hash> std::hash::Hash for EntityRef<T, P> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        T::KIND.hash(state);
        self.id.hash(state);
        self.parent.hash(state);
    }
}

impl<T: Entity, P: ParentKind + Clone> Clone for EntityRef<T, P> {
    fn clone(&self) -> Self {
        Self { id: self.id.clone(), parent: self.parent.clone(), _marker: PhantomData }
    }
}

impl<T: Entity, P: ParentKind + std::fmt::Debug> std::fmt::Debug for EntityRef<T, P> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EntityRef")
            .field("kind", &T::KIND)
            .field("id", &self.id)
            .field("parent", &self.parent)
            .finish()
    }
}

// ---------------------------------------------------------------------------
// EntityRef Serialize / Deserialize
// ---------------------------------------------------------------------------

impl<T: Entity, P: ParentKind> serde::Serialize for EntityRef<T, P> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        let mut map = s.serialize_map(None)?;
        map.serialize_entry("id", &self.id)?;
        map.serialize_entry("kind", T::KIND.as_str())?;
        self.parent.serialize_parent(&mut map)?;
        map.end()
    }
}

impl<'de, T: Entity, P: ParentKind> serde::Deserialize<'de> for EntityRef<T, P> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{MapAccess, Visitor};
        use std::fmt;

        struct V<T, P>(std::marker::PhantomData<(T, P)>);

        impl<'de, T: Entity, P: ParentKind> Visitor<'de> for V<T, P> {
            type Value = EntityRef<T, P>;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "an entity ref object")
            }

            fn visit_map<A: MapAccess<'de>>(
                self,
                mut map: A,
            ) -> Result<EntityRef<T, P>, A::Error> {
                let mut id: Option<String> = None;
                let mut kind: Option<String> = None;
                let mut parent: Option<serde_json::Value> = None;
                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "id" => id = Some(map.next_value()?),
                        "kind" => kind = Some(map.next_value()?),
                        "parent" => parent = Some(map.next_value()?),
                        _ => { let _: serde_json::Value = map.next_value()?; }
                    }
                }
                let id = id.ok_or_else(|| serde::de::Error::missing_field("id"))?;
                let kind = kind.ok_or_else(|| serde::de::Error::missing_field("kind"))?;
                if kind != T::KIND.as_str() {
                    return Err(serde::de::Error::custom(format!(
                        "entity kind mismatch: expected {}, got {}",
                        T::KIND.as_str(),
                        kind,
                    )));
                }
                let parent = P::deserialize_parent(parent)?;
                Ok(EntityRef::with_parent(id, parent))
            }
        }

        d.deserialize_map(V::<T, P>(std::marker::PhantomData))
    }
}

impl WorkflowParent {
    pub fn to_any_ref(&self) -> AnyEntityRef {
        match self {
            WorkflowParent::Workflow(r) => AnyEntityRef::Workflow(r.clone()),
            WorkflowParent::ReusableWorkflow(r) => AnyEntityRef::ReusableWorkflow(r.clone()),
            WorkflowParent::EmbeddedWorkflow(r) => AnyEntityRef::EmbeddedWorkflow((**r).clone()),
        }
    }
}


// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    // --- ParentKind ---

    #[test]
    fn no_parent_instances_are_equal() {
        assert_eq!(NoParent, NoParent);
    }

    #[test]
    fn workflow_parent_equality_based_on_parent_ref() {
        let a = WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow"));
        let b = WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow"));
        let c = WorkflowParent::Workflow(EntityRef::<Workflow>::new("OtherWorkflow"));
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    // --- EntityKind ---

    #[test]
    fn entity_kind_variants_are_copy() {
        let k = EntityKind::Role;
        let k2 = k; // copy, no move
        assert_eq!(k, k2);
    }

    #[test]
    fn entity_kind_variants_are_distinct() {
        assert_ne!(EntityKind::Role, EntityKind::Hook);
        assert_ne!(EntityKind::Task, EntityKind::Relay);
    }

    // --- EntityRef for top-level entity (stubbed entity type) ---

    struct TestEntity;
    impl Entity for TestEntity {
        const KIND: EntityKind = EntityKind::Role;
        fn validation_schema() -> &'static ValidationSchema<Self> {
            static S: std::sync::OnceLock<ValidationSchema<TestEntity>> = std::sync::OnceLock::new();
            S.get_or_init(ValidationSchema::empty)
        }
        type Parent = NoParent;
        type Tracked = TestTrackedEntity;
        fn to_any_ref(_: &EntityRef<Self, Self::Parent>) -> AnyEntityRef { unimplemented!() }
        fn extract(_: &StoreEntity) -> Option<&Self::Tracked> { unimplemented!() }
    }
    struct TestTrackedEntity;
    impl TrackedFor for TestTrackedEntity {
        type Entity = TestEntity;
    }

    #[test]
    fn entity_ref_id_roundtrip() {
        let r: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        assert_eq!(r.id(), "eng-lead");
    }

    #[test]
    fn entity_ref_equality_same_id() {
        let a: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        let b: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        assert_eq!(a, b);
    }

    #[test]
    fn entity_ref_inequality_different_id() {
        let a: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        let b: EntityRef<TestEntity> = EntityRef::new("pm");
        assert_ne!(a, b);
    }

    #[test]
    fn entity_ref_usable_as_hashmap_key() {
        let mut map: HashMap<EntityRef<TestEntity>, u32> = HashMap::new();
        let r = EntityRef::new("eng-lead");
        map.insert(r.clone(), 42);
        assert_eq!(map[&r], 42);
    }

    #[test]
    fn top_level_entity_ref_parent_is_none() {
        let r: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        assert!(r.parent().is_none());
    }

    // --- Embedded EntityRef ---

    struct EmbeddedTest;
    impl Entity for EmbeddedTest {
        const KIND: EntityKind = EntityKind::Task;
        fn validation_schema() -> &'static ValidationSchema<Self> {
            static S: std::sync::OnceLock<ValidationSchema<EmbeddedTest>> = std::sync::OnceLock::new();
            S.get_or_init(ValidationSchema::empty)
        }
        type Parent = WorkflowParent;
        type Tracked = EmbeddedTracked;
        fn to_any_ref(_: &EntityRef<Self, Self::Parent>) -> AnyEntityRef { unimplemented!() }
        fn extract(_: &StoreEntity) -> Option<&Self::Tracked> { unimplemented!() }
    }
    struct EmbeddedTracked;
    impl TrackedFor for EmbeddedTracked {
        type Entity = EmbeddedTest;
    }

    #[test]
    fn embedded_entity_ref_equality_requires_matching_parent() {
        let a = EntityRef::<EmbeddedTest, WorkflowParent>::with_parent(
            "WriteProposal",
            WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow")),
        );
        let b = EntityRef::<EmbeddedTest, WorkflowParent>::with_parent(
            "WriteProposal",
            WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow")),
        );
        let c = EntityRef::<EmbeddedTest, WorkflowParent>::with_parent(
            "WriteProposal",
            WorkflowParent::Workflow(EntityRef::<Workflow>::new("OtherWorkflow")),
        );
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn embedded_entity_ref_parent_is_some() {
        let r = EntityRef::<EmbeddedTest, WorkflowParent>::with_parent(
            "WriteProposal",
            WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow")),
        );
        assert!(matches!(
            r.parent(),
            Some(WorkflowParent::Workflow(parent)) if parent.id() == "InitiativeWorkflow"
        ));
    }

    #[test]
    fn entity_ref_serde_roundtrip_top_level() {
        let original: EntityRef<Workflow> = EntityRef::new("InitiativeWorkflow");
        let json = serde_json::to_value(&original).unwrap();
        assert_eq!(json, serde_json::json!({
            "id": "InitiativeWorkflow",
            "kind": "Workflow",
        }));

        let decoded: EntityRef<Workflow> = serde_json::from_value(json).unwrap();
        assert_eq!(decoded, original);
    }

    #[test]
    fn entity_ref_serde_roundtrip_embedded_with_recursive_parent() {
        let parent = WorkflowParent::EmbeddedWorkflow(Box::new(
            EntityRef::<EmbeddedWorkflow, WorkflowParent>::with_parent(
                "SubWorkflow",
                WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow")),
            ),
        ));
        let original: EntityRef<EmbeddedTest, WorkflowParent> =
            EntityRef::with_parent("WriteProposal", parent);

        let json = serde_json::to_value(&original).unwrap();
        assert_eq!(json, serde_json::json!({
            "id": "WriteProposal",
            "kind": "Task",
            "parent": {
                "id": "SubWorkflow",
                "kind": "EmbeddedWorkflow",
                "parent": {
                    "id": "InitiativeWorkflow",
                    "kind": "Workflow",
                }
            }
        }));

        let decoded: EntityRef<EmbeddedTest, WorkflowParent> = serde_json::from_value(json).unwrap();
        assert_eq!(decoded, original);
    }

    #[test]
    fn entity_ref_deserialize_rejects_kind_mismatch() {
        let err = serde_json::from_value::<EntityRef<Workflow>>(serde_json::json!({
            "id": "InitiativeWorkflow",
            "kind": "Role",
        }))
        .unwrap_err();
        assert!(err.to_string().contains("entity kind mismatch"));
    }

    #[test]
    fn entity_ref_deserialize_rejects_parent_for_top_level_refs() {
        let err = serde_json::from_value::<EntityRef<Workflow>>(serde_json::json!({
            "id": "InitiativeWorkflow",
            "kind": "Workflow",
            "parent": {
                "id": "ParentWorkflow",
                "kind": "Workflow",
            }
        }))
        .unwrap_err();
        assert!(err.to_string().contains("unknown field"));
    }

    #[test]
    fn workflow_parent_to_any_ref_preserves_parent_variant() {
        let workflow_parent =
            WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow"));
        let reusable_parent = WorkflowParent::ReusableWorkflow(
            EntityRef::<ReusableWorkflow>::new("CommonFlow"),
        );
        let embedded_parent = WorkflowParent::EmbeddedWorkflow(Box::new(
            EntityRef::<EmbeddedWorkflow, WorkflowParent>::with_parent(
                "SubWorkflow",
                WorkflowParent::Workflow(EntityRef::<Workflow>::new("InitiativeWorkflow")),
            ),
        ));

        assert!(matches!(
            workflow_parent.to_any_ref(),
            AnyEntityRef::Workflow(r) if r.id() == "InitiativeWorkflow"
        ));
        assert!(matches!(
            reusable_parent.to_any_ref(),
            AnyEntityRef::ReusableWorkflow(r) if r.id() == "CommonFlow"
        ));
        assert!(matches!(
            embedded_parent.to_any_ref(),
            AnyEntityRef::EmbeddedWorkflow(r) if r.id() == "SubWorkflow"
        ));
    }

    // --- Tracked<T> alias ---

    #[test]
    fn tracked_alias_resolves_to_tracked_entity() {
        fn _check(_: Tracked<TestEntity>) {}
        let _ = |t: TestTrackedEntity| _check(t);
    }

    // --- EntityKind (generated by entity_registry!) ---

    #[test]
    fn entity_kind_all_variants_distinct() {
        let kinds = [
            EntityKind::Role, EntityKind::Hook, EntityKind::Team,
            EntityKind::Workflow, EntityKind::ReusableWorkflow, EntityKind::ArtifactKind,
            EntityKind::Task, EntityKind::Relay, EntityKind::EmbeddedWorkflow,
        ];
        for (i, a) in kinds.iter().enumerate() {
            for (j, b) in kinds.iter().enumerate() {
                if i != j { assert_ne!(a, b); }
            }
        }
    }

    #[test]
    fn entity_kind_all_variants_is_copy() {
        let k = EntityKind::Workflow;
        let k2 = k;
        assert_eq!(k, k2);
    }

    // --- load_strategy (generated by entity_registry!) ---

    #[test]
    fn load_strategy_returns_correct_kind_for_each_entity() {
        assert_eq!(load_strategy(EntityKind::Role).kind(),             EntityKind::Role);
        assert_eq!(load_strategy(EntityKind::Hook).kind(),             EntityKind::Hook);
        assert_eq!(load_strategy(EntityKind::Team).kind(),             EntityKind::Team);
        assert_eq!(load_strategy(EntityKind::Workflow).kind(),         EntityKind::Workflow);
        assert_eq!(load_strategy(EntityKind::ReusableWorkflow).kind(), EntityKind::ReusableWorkflow);
        assert_eq!(load_strategy(EntityKind::ArtifactKind).kind(),     EntityKind::ArtifactKind);
        assert_eq!(load_strategy(EntityKind::Task).kind(),             EntityKind::Task);
        assert_eq!(load_strategy(EntityKind::Relay).kind(),            EntityKind::Relay);
        assert_eq!(load_strategy(EntityKind::EmbeddedWorkflow).kind(), EntityKind::EmbeddedWorkflow);
    }

    // --- AnyEntityRef (compile-time checks; runtime tests deferred to Task 05) ---

    #[test]
    fn any_entity_ref_kind_id_parent_methods_exist() {
        // Verify methods are present by taking function pointers
        let _: fn(&AnyEntityRef) -> EntityKind = AnyEntityRef::kind;
        let _: fn(&AnyEntityRef) -> &str       = AnyEntityRef::id;
    }
}
