//! Entity identity infrastructure.
//!
//! [`Entity`] — core trait every entity type implements.
//! [`TrackedFor`] — companion trait linking `Tracked*` structs back to their entity type.
//! [`EntityRef`] — typed reference (id + optional parent chain).
//! [`EntityKind`] — discriminant enum for all entity types.
//! [`StoreEntity`] — store-level enum wrapping all tracked entity types.
//! [`ParentKind`] — sealed marker for parent type parameters.

use std::marker::PhantomData;

// ---------------------------------------------------------------------------
// Re-exports from validation module (Task 06)
// ---------------------------------------------------------------------------

// ValidationSchema, LoadError, SetterError re-exported so that proc-macro
// generated code using `::pari::entity::ValidationSchema` etc. resolves here.
pub use crate::validation::{LoadError, SetterError, SubstrateError, ValidationSchema};

// ---------------------------------------------------------------------------
// Sealed
// ---------------------------------------------------------------------------

mod private {
    pub trait Sealed {}
}

// ---------------------------------------------------------------------------
// ParentKind
// ---------------------------------------------------------------------------

/// Marker trait for parent type parameters on EntityRef.
pub trait ParentKind: private::Sealed {}

/// Top-level entities have no parent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NoParent;
impl private::Sealed for NoParent {}
impl ParentKind for NoParent {}

/// Embedded entities (Task, Relay, EmbeddedWorkflow) live inside a workflow.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WorkflowParent {
    /// The id of the containing workflow.
    pub workflow_id: String,
}
impl private::Sealed for WorkflowParent {}
impl ParentKind for WorkflowParent {}

// ---------------------------------------------------------------------------
// Real entity types — imported from crate::entities (Task 05+).
// EntityKind, AnyEntityRef, StoreEntity, SubstrateSchema, and load_strategy
// are all generated by the entity_registry! invocation below.
// ---------------------------------------------------------------------------

use crate::entities::{
    artifact_kind::{ArtifactKind, TrackedArtifactKind},
    hook::{Hook, TrackedHook},
    relay::{Relay, TrackedRelay},
    role::{Role, TrackedRole},
    task::{Task, TrackedTask},
    team::{Team, TrackedTeam},
    workflow::{
        EmbeddedWorkflow, ReusableWorkflow, TrackedEmbeddedWorkflow, TrackedReusableWorkflow,
        TrackedWorkflow, Workflow,
    },
};

pari_macros::entity_registry! {
    Role             => NoParent,
    Hook             => NoParent,
    Team             => NoParent,
    Workflow         => NoParent,
    ReusableWorkflow => NoParent,
    ArtifactKind     => NoParent,
    Task             => WorkflowParent,
    Relay            => WorkflowParent,
    EmbeddedWorkflow => WorkflowParent,
}

// ---------------------------------------------------------------------------
// Entity trait
// ---------------------------------------------------------------------------

pub trait Entity: Sized + 'static {
    const KIND: EntityKind;
    fn validation_schema() -> &'static ValidationSchema<Self>;
    type Parent: ParentKind;
    type Tracked: TrackedFor<Entity = Self>;

    /// Convert a typed EntityRef to the type-erased AnyEntityRef.
    /// Generated by `#[derive(Entity)]`.
    fn to_any_ref(entity_ref: &EntityRef<Self, Self::Parent>) -> AnyEntityRef;

    /// Extract this entity's tracked form from a StoreEntity.
    /// Returns None if the variant doesn't match.
    /// Generated by `#[derive(Entity)]`.
    fn extract(entity: &StoreEntity) -> Option<&Self::Tracked>;
}

// ---------------------------------------------------------------------------
// TrackedFor companion trait
// ---------------------------------------------------------------------------

/// Implemented by every tracked entity struct.
/// Provides the roundtrip: `TrackedRole::Entity = Role`
/// and therefore `Role::Tracked::Entity = Role`.
pub trait TrackedFor {
    type Entity: Entity<Tracked = Self>;
}

// ---------------------------------------------------------------------------
// Tracked<T> type alias
// ---------------------------------------------------------------------------

/// Ergonomic alias: `Tracked<Role>` instead of `<Role as Entity>::Tracked`.
pub type Tracked<T> = <T as Entity>::Tracked;

// ---------------------------------------------------------------------------
// EntityRef<T, P>
// ---------------------------------------------------------------------------

/// A typed reference to an entity: its string id and optional parent context.
///
/// `T: Entity` ensures only declared entity types can form refs.
/// `P = NoParent` default covers top-level entities.
///
/// Hash and Eq incorporate `T::KIND` so refs of different entity types with
/// the same id do not collide as HashMap keys.
pub struct EntityRef<T: Entity, P: ParentKind = NoParent> {
    pub(crate) id: String,
    pub(crate) parent: P,
    _marker: PhantomData<fn() -> T>,
}

impl<T: Entity> EntityRef<T, NoParent> {
    /// Construct a top-level entity reference.
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into(), parent: NoParent, _marker: PhantomData }
    }
}

impl<T: Entity> EntityRef<T, WorkflowParent> {
    /// Construct an embedded entity reference with its parent workflow id.
    pub fn new_embedded(id: impl Into<String>, workflow_id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            parent: WorkflowParent { workflow_id: workflow_id.into() },
            _marker: PhantomData,
        }
    }
}

impl<T: Entity, P: ParentKind> EntityRef<T, P> {
    pub fn id(&self) -> &str {
        &self.id
    }

    pub fn parent(&self) -> &P {
        &self.parent
    }
}

impl<T: Entity, P: ParentKind + PartialEq> PartialEq for EntityRef<T, P> {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id && self.parent == other.parent
    }
}

impl<T: Entity, P: ParentKind + Eq> Eq for EntityRef<T, P> {}

impl<T: Entity, P: ParentKind + std::hash::Hash> std::hash::Hash for EntityRef<T, P> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        T::KIND.hash(state);
        self.id.hash(state);
        self.parent.hash(state);
    }
}

impl<T: Entity, P: ParentKind + Clone> Clone for EntityRef<T, P> {
    fn clone(&self) -> Self {
        Self { id: self.id.clone(), parent: self.parent.clone(), _marker: PhantomData }
    }
}

impl<T: Entity, P: ParentKind + std::fmt::Debug> std::fmt::Debug for EntityRef<T, P> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EntityRef")
            .field("kind", &T::KIND)
            .field("id", &self.id)
            .field("parent", &self.parent)
            .finish()
    }
}

// ---------------------------------------------------------------------------
// EntityRef Serialize / Deserialize
// ---------------------------------------------------------------------------

impl<T: Entity> serde::Serialize for EntityRef<T, NoParent> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        let mut map = s.serialize_map(Some(2))?;
        map.serialize_entry("id", &self.id)?;
        map.serialize_entry("kind", T::KIND.as_str())?;
        map.end()
    }
}

impl<T: Entity> serde::Serialize for EntityRef<T, WorkflowParent> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        let mut map = s.serialize_map(Some(3))?;
        map.serialize_entry("id", &self.id)?;
        map.serialize_entry("kind", T::KIND.as_str())?;
        map.serialize_entry("workflow_id", &self.parent.workflow_id)?;
        map.end()
    }
}

impl<'de, T: Entity> serde::Deserialize<'de> for EntityRef<T, NoParent> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{MapAccess, Visitor};
        use std::fmt;

        struct V<T>(std::marker::PhantomData<T>);

        impl<'de, T: Entity> Visitor<'de> for V<T> {
            type Value = EntityRef<T, NoParent>;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "an entity ref object")
            }

            fn visit_map<A: MapAccess<'de>>(
                self,
                mut map: A,
            ) -> Result<EntityRef<T, NoParent>, A::Error> {
                let mut id: Option<String> = None;
                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "id" => id = Some(map.next_value()?),
                        _ => { let _: serde_json::Value = map.next_value()?; }
                    }
                }
                let id = id.ok_or_else(|| serde::de::Error::missing_field("id"))?;
                Ok(EntityRef::new(id))
            }
        }

        d.deserialize_map(V::<T>(std::marker::PhantomData))
    }
}

impl<'de, T: Entity> serde::Deserialize<'de> for EntityRef<T, WorkflowParent> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{MapAccess, Visitor};
        use std::fmt;

        struct V<T>(std::marker::PhantomData<T>);

        impl<'de, T: Entity> Visitor<'de> for V<T> {
            type Value = EntityRef<T, WorkflowParent>;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                write!(f, "an embedded entity ref object")
            }

            fn visit_map<A: MapAccess<'de>>(
                self,
                mut map: A,
            ) -> Result<EntityRef<T, WorkflowParent>, A::Error> {
                let mut id: Option<String> = None;
                let mut workflow_id: Option<String> = None;
                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "id" => id = Some(map.next_value()?),
                        "workflow_id" => workflow_id = Some(map.next_value()?),
                        _ => { let _: serde_json::Value = map.next_value()?; }
                    }
                }
                let id = id.ok_or_else(|| serde::de::Error::missing_field("id"))?;
                let workflow_id =
                    workflow_id.ok_or_else(|| serde::de::Error::missing_field("workflow_id"))?;
                Ok(EntityRef::new_embedded(id, workflow_id))
            }
        }

        d.deserialize_map(V::<T>(std::marker::PhantomData))
    }
}


// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    // --- ParentKind ---

    #[test]
    fn no_parent_instances_are_equal() {
        assert_eq!(NoParent, NoParent);
    }

    #[test]
    fn workflow_parent_equality_based_on_workflow_id() {
        let a = WorkflowParent { workflow_id: "InitiativeWorkflow".into() };
        let b = WorkflowParent { workflow_id: "InitiativeWorkflow".into() };
        let c = WorkflowParent { workflow_id: "OtherWorkflow".into() };
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    // --- EntityKind ---

    #[test]
    fn entity_kind_variants_are_copy() {
        let k = EntityKind::Role;
        let k2 = k; // copy, no move
        assert_eq!(k, k2);
    }

    #[test]
    fn entity_kind_variants_are_distinct() {
        assert_ne!(EntityKind::Role, EntityKind::Hook);
        assert_ne!(EntityKind::Task, EntityKind::Relay);
    }

    // --- EntityRef for top-level entity (stubbed entity type) ---

    struct TestEntity;
    impl Entity for TestEntity {
        const KIND: EntityKind = EntityKind::Role;
        fn validation_schema() -> &'static ValidationSchema<Self> {
            static S: std::sync::OnceLock<ValidationSchema<TestEntity>> = std::sync::OnceLock::new();
            S.get_or_init(ValidationSchema::empty)
        }
        type Parent = NoParent;
        type Tracked = TestTrackedEntity;
        fn to_any_ref(_: &EntityRef<Self, Self::Parent>) -> AnyEntityRef { unimplemented!() }
        fn extract(_: &StoreEntity) -> Option<&Self::Tracked> { unimplemented!() }
    }
    struct TestTrackedEntity;
    impl TrackedFor for TestTrackedEntity {
        type Entity = TestEntity;
    }

    #[test]
    fn entity_ref_id_roundtrip() {
        let r: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        assert_eq!(r.id(), "eng-lead");
    }

    #[test]
    fn entity_ref_equality_same_id() {
        let a: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        let b: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        assert_eq!(a, b);
    }

    #[test]
    fn entity_ref_inequality_different_id() {
        let a: EntityRef<TestEntity> = EntityRef::new("eng-lead");
        let b: EntityRef<TestEntity> = EntityRef::new("pm");
        assert_ne!(a, b);
    }

    #[test]
    fn entity_ref_usable_as_hashmap_key() {
        let mut map: HashMap<EntityRef<TestEntity>, u32> = HashMap::new();
        let r = EntityRef::new("eng-lead");
        map.insert(r.clone(), 42);
        assert_eq!(map[&r], 42);
    }

    // --- Embedded EntityRef ---

    struct EmbeddedTest;
    impl Entity for EmbeddedTest {
        const KIND: EntityKind = EntityKind::Task;
        fn validation_schema() -> &'static ValidationSchema<Self> {
            static S: std::sync::OnceLock<ValidationSchema<EmbeddedTest>> = std::sync::OnceLock::new();
            S.get_or_init(ValidationSchema::empty)
        }
        type Parent = WorkflowParent;
        type Tracked = EmbeddedTracked;
        fn to_any_ref(_: &EntityRef<Self, Self::Parent>) -> AnyEntityRef { unimplemented!() }
        fn extract(_: &StoreEntity) -> Option<&Self::Tracked> { unimplemented!() }
    }
    struct EmbeddedTracked;
    impl TrackedFor for EmbeddedTracked {
        type Entity = EmbeddedTest;
    }

    #[test]
    fn embedded_entity_ref_equality_requires_matching_parent() {
        let a = EntityRef::<EmbeddedTest, WorkflowParent>::new_embedded(
            "WriteProposal",
            "InitiativeWorkflow",
        );
        let b = EntityRef::<EmbeddedTest, WorkflowParent>::new_embedded(
            "WriteProposal",
            "InitiativeWorkflow",
        );
        let c = EntityRef::<EmbeddedTest, WorkflowParent>::new_embedded(
            "WriteProposal",
            "OtherWorkflow",
        );
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    // --- Tracked<T> alias ---

    #[test]
    fn tracked_alias_resolves_to_tracked_entity() {
        fn _check(_: Tracked<TestEntity>) {}
        let _ = |t: TestTrackedEntity| _check(t);
    }

    // --- EntityKind (generated by entity_registry!) ---

    #[test]
    fn entity_kind_all_variants_distinct() {
        let kinds = [
            EntityKind::Role, EntityKind::Hook, EntityKind::Team,
            EntityKind::Workflow, EntityKind::ReusableWorkflow, EntityKind::ArtifactKind,
            EntityKind::Task, EntityKind::Relay, EntityKind::EmbeddedWorkflow,
        ];
        for (i, a) in kinds.iter().enumerate() {
            for (j, b) in kinds.iter().enumerate() {
                if i != j { assert_ne!(a, b); }
            }
        }
    }

    #[test]
    fn entity_kind_all_variants_is_copy() {
        let k = EntityKind::Workflow;
        let k2 = k;
        assert_eq!(k, k2);
    }

    // --- load_strategy (generated by entity_registry!) ---

    #[test]
    fn load_strategy_returns_correct_kind_for_each_entity() {
        assert_eq!(load_strategy(EntityKind::Role).kind(),             EntityKind::Role);
        assert_eq!(load_strategy(EntityKind::Hook).kind(),             EntityKind::Hook);
        assert_eq!(load_strategy(EntityKind::Team).kind(),             EntityKind::Team);
        assert_eq!(load_strategy(EntityKind::Workflow).kind(),         EntityKind::Workflow);
        assert_eq!(load_strategy(EntityKind::ReusableWorkflow).kind(), EntityKind::ReusableWorkflow);
        assert_eq!(load_strategy(EntityKind::ArtifactKind).kind(),     EntityKind::ArtifactKind);
        assert_eq!(load_strategy(EntityKind::Task).kind(),             EntityKind::Task);
        assert_eq!(load_strategy(EntityKind::Relay).kind(),            EntityKind::Relay);
        assert_eq!(load_strategy(EntityKind::EmbeddedWorkflow).kind(), EntityKind::EmbeddedWorkflow);
    }

    // --- AnyEntityRef (compile-time checks; runtime tests deferred to Task 05) ---

    #[test]
    fn any_entity_ref_kind_id_parent_methods_exist() {
        // Verify methods are present by taking function pointers
        let _: fn(&AnyEntityRef) -> EntityKind = AnyEntityRef::kind;
        let _: fn(&AnyEntityRef) -> &str       = AnyEntityRef::id;
    }
}
